#!/bin/sh

#x="$(pwd)"
#filetovim=$x/$1
#vim filetovim
#docker run -it --rm vim vim filetovim

#alias vim to python /path_to/pvim pwd filename

#python pvim.py "$(pwd)" $1

#alias ls='ls --color=auto'
#alias vim='docker run -it --rm -v /Users/brandomiranda/home_simulation_research:/home_simulation_research vim_img python3 /home_simulation_research/hbf_tensorflow_code/docker_files/vim_img/pvim.py $(pwd) $1'
#alias vim='docker run -it --rm -v /raid/poggio/home/brando90/home_simulation_research/home_simulation_research:/home_simulation_research vim_img python3 /home_simulation_research/hbf_tensorflow_code/docker_files/vim_img/pvim.py $(pwd) $1'


#docker run -it --rm -v /Users/brandomiranda/home_simulation_research:/home_simulation_research vim python /home_simulation_research/hbf_tensorflow_code/docker_files/vim/pvim.py "$(pwd)" $1
docker run -it --rm -v /Users/brandomiranda/home_simulation_research:/home_simulation_research vim_img python3 /home_simulation_research/hbf_tensorflow_code/docker_files/vim_img/pvim.py $(pwd) $1
#docker run -it --rm vim bash
