FROM ubuntu

#RUN ls .
#CMD echo

#RUN mkdir /BRANDO

#ENTRYPOINT ls /dir_container_side
#ENTRYPOINT cat /dir_container_side/hello.txt
#ENTRYPOINT exec echo "echo hello world"
#RUN cat /dir_container_side/hello.txt
ENTRYPOINT ["sh", "/dir_container_side/bash_stuff.sh"]
#ENTRYPOINT ["echo"]
