# This means you derive your docker image from the tensorflow docker image
# FROM gcr.io/tensorflow/tensorflow:latest-devel-gpu
FROM gcr.io/tensorflow/tensorflow
FROM python
FROM ubuntu

#
#RUN pip install numpy
#RUN pip install keras
#RUN pip install namespaces
#RUN pip install pdb
#RUN pip install ../../my_tf_proj/
#RUN pip install /Users/brandomiranda/Documents/MIT/MEng/hbf_tensorflow_code/my_tf_proj
